apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.reactapp.name }}
  labels:
    app: {{ template "reactapp.name" . }}
    chart: {{ template "bank-operations.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.reactapp.type }}
  ports:
    - port: {{ .Values.service.reactapp.externalPort }}
      targetPort: {{ .Values.service.reactapp.internalPort }}
      protocol: {{ .Values.service.reactapp.protocol }}
      name: {{ .Values.service.reactapp.name }}
  selector:
    app: {{ template "reactapp.name" . }}
    release: {{ .Release.Name }}