apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.springapp.name }}
  labels:
    app: {{ template "springapp.name" . }}
    chart: {{ template "bank-operations.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.springapp.type }}
  ports:
    - port: {{ .Values.service.springapp.externalPort }}
      targetPort: {{ .Values.service.springapp.internalPort }}
      protocol: {{ .Values.service.springapp.protocol }}
      name: {{ .Values.service.springapp.name }}
  selector:
    app: {{ template "springapp.name" . }}
    release: {{ .Release.Name }}