apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "springapp.name" . }}
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.springapp.host }}
      http:
        paths:
          - path: {{ .Values.ingress.springapp.path }}
            backend:
              serviceName: {{ .Values.service.springapp.name }}
              servicePort: {{ .Values.service.springapp.externalPort }}